### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by dongleihu** [MMAP/MMAP-releases-issues-Q-and-A#4]
I was trying to use "--combine_binary_genotype_files" to combine 2 chromosomes.  There are 2000 individuals and each chromosome has about 110k SNPs.  I've required 100G for memory but I got an error message saying "28002 Segmentation fault".  Any suggestions?  Thanks.

**Comment by jeffoconnell496** [comment]
Hi Donglei,
I haven't used that option in several years so I don't have any immediate
insight into potential problem. We can try to reproduce the problem here,
but given you smallish sample size a work around would be to export the
binary files to csv file, then concatenate (remove 1 header), then convert
back to binary.
Hope this helps,
Jeff

**Comment by dongleihu** [comment]
Hi Jeff,

Thanks for the tip.  I will try.

Donglei
